### PR TITLE
404 Page

### PR DESCRIPTION
**Pull request by DJam98**
Add a 404 page, with a broken Off the Dial image as well.

### CODE REVIEW

**Comment by DJam98** [comment]
What do you think of this 404 page?

**Comment by DJam98** [comment]
@LeptoFlare

**Comment by DJam98** [comment]
Done with that, could you take another look @LeptoFlare

**Comment by LeptoFlare** [comment]
We shouldn't be doing that with the CSS

**Comment by DJam98** [comment]
I don't really know how to do that. MD is a very different language to HTML and it needs the CSS or else it looks absolutely horrible.

**Comment by LeptoFlare** [comment]
@Djam98 Updated the 404 page before merging

**Pull request merged**
