### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by DJam98**
Front end of a form has been created. Includes html and css

### CODE REVIEW

**Comment by DJam98** [comment]
Can you create a backend that will make this form email to my @LeptoFlare and check that this seems right?

**Comment by DJam98** [comment]
Note: I've added some other things into the CSS so that proportions are right. It's not just the website thing.

**Comment by LeptoFlare** [comment]
Feel like we're reinventing the wheel here.
Maybe it would be best to just hotlink it to the form.
such as `https://otd.ink/feedback` would automatically link to the form.

**Comment by DJam98** [comment]
It's also a matter of just porting everything to the site. Eventually, it would be best if we just got rid of anything public that needed to use other services (excluding discord, smashgg, Github, etc). I did a bit of research of what the backend looks like but I have no idea how to use java and PHP. [https://html.form.guide/email-form/dreamweaver-email-form.html](https://html.form.guide/email-form/dreamweaver-email-form.html)

**Comment by LeptoFlare** [comment]
Google Forms and Typeform etc have really great features.

I don't think porting everything to the site should be the goal.
Just centralizing where to *find* all of the services is what we should do.

**Comment by LeptoFlare** [comment]
Personally I think we should use Typeform, and have a full-page embed

**Comment by DJam98** [comment]
It's now a typeform

**Comment by DJam98** [comment]
@LeptoFlare

**Pull request merged**
