### PR TITLE
Guidelines for Commentators and Streamers

### PR DESCRIPTION
**Pull request by DJam98**

### CODE REVIEW

**Comment by LeptoFlare** [comment]
I don't think this is a good idea, because it's completely public.

Maybe it would be better if we made a separate repository for hosting internal guidelines.

**Comment by DJam98** [comment]
It's not going to be linked on the page. Similar to how legal is now, it would just be accessible via a link. Also, it's not a huge issue if someone does find it. All they would find out is the guidelines we have for streaming and commentating.

**Comment by DJam98** [comment]
The only one for someone to find it if they weren't given the link would be to find it on here on the GitHub page.

**Comment by LeptoFlare** [comment]
Another gripe I have with this is that we should not be responsible of making sure that the commentator is doing a good job. If a commentator does not do fundamental things such as be unbiased or stay professional, we simply do not put the on board.

This page should only be for Off the Dial specific concerns for commentators and streamers

**Pull request closed without merging**
